name: contentful
version: "3.0.5"
description: Contentful Delivery API client for Dart. This Dart package is a small abstraction on top of the Contentful Delivery API.
homepage: https://gitlab.com/arisechurch/dart-contentful
repository: https://gitlab.com/arisechurch/dart-contentful

environment:
  sdk: ">=2.12.0 <3.16.5"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.1.2
  json_annotation: ^4.8.1
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  collection: ^1.18.0
  json_serializable: ^6.7.1
  pedantic: ^1.11.1
  mocktail: ^1.0.2
